# .gitlab-ci.yml

stages:
  - build
  - deploy

variables:
  GCP_PROJECT_ID: samsung-mx-test 
  GCP_REGION: asia-northeast3
  ARTIFACT_REGISTRY: my-repo
  SERVICE_NAME: hello-spring-boot
  IMAGE_TAG: $CI_COMMIT_SHA

build_and_deploy:
  stage: deploy
  tags:
    - test
  image: google/cloud-sdk:latest
  services:
    - docker:dind
  script:
    # 1. GCP 서비스 계정 키 내용을 임시 파일에 저장합니다.
    - echo "$GCP_SA_KEY" > /tmp/gcp_key.json
    
    # 2. 임시 파일의 경로를 사용해 gcloud CLI를 인증합니다.
    - gcloud auth activate-service-account --key-file=/tmp/gcp_key.json
    
    # 3. Docker가 Artifact Registry에 인증할 수 있도록 설정합니다.
    - gcloud auth configure-docker $GCP_REGION-docker.pkg.dev
    
    # 4. Docker 이미지 빌드 및 푸시
    - docker build -t $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REGISTRY/$SERVICE_NAME:$IMAGE_TAG .
    - docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REGISTRY/$SERVICE_NAME:$IMAGE_TAG
    
    # 5. Cloud Run에 배포
    - gcloud run deploy $SERVICE_NAME --image $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REGISTRY/$SERVICE_NAME:$IMAGE_TAG --platform managed --region $GCP_REGION --allow-unauthenticated