# .gitlab-ci.yml

stages:
  - build
  - deploy

variables:
  GCP_PROJECT_ID: samsung-mx-test 
  GCP_REGION: asia-northeast3
  ARTIFACT_REGISTRY: my-repo
  SERVICE_NAME: hello-spring-boot

build_and_deploy:
  stage: deploy
  tags:
    - test
  image: docker:latest
  services:
    - docker:dind
  script:
    - gcloud auth activate-service-account --key-file=$GCP_SA_KEY
    # Docker가 Artifact Registry에 인증할 수 있도록 gcloud 자격 증명 도우미를 설정
    - gcloud auth configure-docker asia-northeast3-docker.pkg.dev
    #- export IMAGE_TAG="$CI_COMMIT_SHA"
    #- docker login -u _json_key --password-stdin https://$GCP_REGION-docker.pkg.dev < $GCP_SA_KEY
    - docker build -t $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REGISTRY/$SERVICE_NAME:$IMAGE_TAG .
    - docker push $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REGISTRY/$SERVICE_NAME:$IMAGE_TAG
    - docker run -d --name test -p 8080:8080 $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REGISTRY/$SERVICE_NAME:$IMAGE_TAG
    - curl http://localhost:8080
    - docker stop test && docker rm test
    - gcloud auth activate-service-account --key-file=$GCP_SA_KEY
    - gcloud run deploy $SERVICE_NAME --image $GCP_REGION-docker.pkg.dev/$GCP_PROJECT_ID/$ARTIFACT_REGISTRY/$SERVICE_NAME:$IMAGE_TAG --platform managed --region $GCP_REGION --allow-unauthenticated
  only:
    - main