steps:
  # Backend Docker 빌드 + Cloud Run 배포
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/backend', './backend']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'backend-service',
           '--image', 'gcr.io/$PROJECT_ID/backend',
           '--region', 'asia-northeast3',
           '--platform', 'managed',
           '--allow-unauthenticated']

  # Frontend Docker 빌드 + Cloud Run 배포
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/frontend', './frontend']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: ['run', 'deploy', 'frontend-service',
           '--image', 'gcr.io/$PROJECT_ID/frontend',
           '--region', 'asia-northeast3',
           '--platform', 'managed',
           '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/backend'
  - 'gcr.io/$PROJECT_ID/frontend'
